env:
  browser: true
  node: true
  es2021: true

ignorePatterns:
  - 'public/**/*.js'
  - '.cache/**/*.js'
  - 'src/pages/**/*.mdx'

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:mdx/recommended
  - plugin:prettier/recommended
  - plugin:react/recommended

settings:
  'mdx/code-blocks':
    - true

parser: "@typescript-eslint/parser"

rules:
  "react/prop-types":
    - "off"
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
  arrow-parens:
    - error
    - always
  curly:
    - error
    - all
  no-else-return:
    - error
    - allowElseIf: false
  no-duplicate-imports:
    - error
    - includeExports: true
  jsx-quotes:
    - error
    - prefer-double
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/indent':
    - off
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  import/no-unresolved:
    - off
  import/no-default-export:
    - off
