env:
  browser: true
  node: true
  es2021: true

ignorePatterns:
  - 'public/'
  - '.cache/'

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended

overrides:
  - files:
    - gatsby-config.ts
    - index.d.ts
    - src/pages/**
    - src/templates/**
    rules:
      import/no-default-export:
      - off

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
  arrow-parens:
    - error
    - always
  curly:
    - error
    - all
  no-else-return:
    - error
    - allowElseIf: false
  no-duplicate-imports:
    - error
    - includeExports: true
  jsx-quotes:
    - error
    - prefer-double
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
    - avoidEscape: true
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/indent':
    - off
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  import/no-unresolved:
    - off
  import/no-default-export:
    - error
  no-restricted-syntax:
    - error
    - selector: SwitchCase > *.consequent[type!="BlockStatement"]
      message: Switch cases without blocks are forbidden.
    - selector: ExportAllDeclaration,ImportAllDeclaration
      message: Export/Import all (*) is forbidden.
    - selector: ExportNamedDeclaration[declaration!=null]
      message: Exports should be at the end of the file.
    - selector: ImportDeclaration[importKind=type],ExportNamedDeclaration[exportKind=type]
      message: Avoid import/export type { Type } from './module'. Prefer import/export { type Type } from './module'.
