name: Continuous Integration

on:
  pull_request:
    branches:
      - development
      - production
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: |
          npm install

      - name: Lint Code
        run: |
          npm run lint
